name: CI
on: [push, pull_request]

jobs:
  # unit-tests:
  #   runs-on: windows-latest
  #   timeout-minutes: 5

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: recursive

  #     - name: Install Studio
  #       uses: OrbitalOwen/roblox-win-installer@1.1
  #       with:
  #         cookie: ${{ secrets.ROBLOSECURITY }}
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Setup Toolchain
  #       uses: Roblox/setup-foreman@v1
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build Test Project
  #       run: rojo build test.project.json -o unit-tests.rbxlx

  #     - name: Run Unit Tests
  #       run: run-in-roblox --place unit-tests.rbxlx --script test/test-runner.server.lua

  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[release]')
    #  needs: [unit-tests]
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Toolchain
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Current Version
        run: |
          PROJECT_VERSION=`grep -Po '(?<=version = ")([^"]+)' wally.toml`
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV

      - name: Get Current Commit ID
        run: |
          PROJECT_COMMIT_ID=`git rev-parse --short ${{ github.sha }}`
          echo "PROJECT_COMMIT_ID=$PROJECT_COMMIT_ID" >> $GITHUB_ENV

      - name: Build Project
        run: |
          rojo build default.project.json -o release.rbxmx
          rojo build default.project.json -o release.rbxm

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.PROJECT_VERSION }}
          body: ${{ env.PROJECT_COMMIT_ID }}
          tag_name: ${{ env.PROJECT_VERSION }}
          files: |
            release.rbxm
            release.rbxmx
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
